[toolchain]
anchor_version = "0.30.0"
[features]
resolution = true
skip-lint = false

[programs.localnet]
solticket = "DGHh1S6VCBmgY4R3Upm6wqV2ADTgEqPvYfgwBqxEW82e"

[programs.devnet]
solticket = "DGHh1S6VCBmgY4R3Upm6wqV2ADTgEqPvYfgwBqxEW82e"

[registry]
url = "https://api.apr.dev"

[provider]

cluster = "devnet"
#cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
