[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solticket = "Bn3L15y9EiCGkGYK3nu98jcqw6n8uTjoBWKeJna1eMdm"

[programs.devnet]
solticket = "Bn3L15y9EiCGkGYK3nu98jcqw6n8uTjoBWKeJna1eMdm"

[registry]
url = "https://api.apr.dev"

[provider]

cluster = "devnet"
#cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
